title: MLphys
description: Machine Learning in Physics — Fall 2026

url: "https://jarek-pawlowski.github.io"
baseurl: "/MLphys_2026"

repository: jarek-pawlowski/MLphys_2026

theme: jekyll-theme-minimal

markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

show_downloads: false

github:
  repository_url: https://github.com/jarek-pawlowski/MLphys_2026

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/